// Generated by CoffeeScript 1.3.3
(function() {
  var app, express, fs,
    _this = this;

  express = require('express');

  fs = require('fs');

  app = express();

  app.configure(function() {
    app.set('views', __dirname + "js/views");
    app.set('view engine', 'jade');
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express.cookieParser());
    return app.use(express["static"](__dirname));
  });

  app.get("/", function(req, res) {
    res.set('Content-type', 'text/html');
    return res.send(index);
  });

  console.log('server listening at 8020');

  app.listen(8020);

}).call(this);
