// Generated by CoffeeScript 1.3.3
(function() {

  define(['backbone', 'views/NewPattern', 'views/PatternListView', 'text!views/templates/navBar.html'], function(Backbone, NewPattern, PatternListView, navBar) {
    var View;
    return View = Backbone.View.extend({
      className: 'masterView',
      el: 'body',
      initialize: function() {
        console.log('assigning views to children');
        this.children = {
          patternList: new PatternListView({
            collection: this.collection
          }),
          newPattern: new NewPattern({
            collection: this.collection
          })
        };
        console.log('hiding el');
        this.$el.hide();
        this.$el.append(navBar);
        this.$el.append(this.children.newPattern.render().el);
        return this.$el.append(this.children.patternList.render().el);
      },
      render: function() {
        this.$el.show();
        return this;
      }
    });
  });

}).call(this);
