// Generated by CoffeeScript 1.3.3
(function() {

  define(['backbone'], function(Backbone) {
    var View, template;
    template = '<input type="text" placeholder="Write pattern name here!"/>';
    View = Backbone.View.extend({
      tagName: 'form',
      className: 'newPattern',
      render: function() {
        this.$el.html(template);
        this.$input = this.$("input");
        return this;
      },
      events: {
        'submit': function(e) {
          e.preventDefault();
          this.collection.create({
            name: this.$input.val().trim()
          });
          return this.$input.val("");
        }
      }
    });
    return View;
  });

}).call(this);
