// Generated by CoffeeScript 1.3.3
(function() {

  define(['backbone', 'views/PatternView'], function(Backbone, PatternView) {
    var View;
    View = Backbone.View.extend({
      tagName: 'ul',
      className: 'patternList',
      initialize: function() {
        this.collection.on('reset', this.render, this);
        return this.collection.on('add', this.add, this);
      },
      render: function() {
        var _this = this;
        console.log('collection:');
        console.log(this.collection);
        this.collection.each(function(pattern) {
          var child;
          console.log('creando new pattern con model=');
          console.log(pattern);
          child = new PatternView({
            model: pattern
          });
          console.log('añadiendo patternview a');
          console.log(_this.$el);
          return _this.$el.append(child.render().$el).show();
        });
        return this;
      }
    });
    return View;
  });

}).call(this);
