// Generated by CoffeeScript 1.3.3
(function() {

  define(['backbone', 'views/PatternView'], function(Backbone, PatternView) {
    var View, separatorTmpl;
    separatorTmpl = _.template('<li class="nav-header"><%= category %></li>');
    View = Backbone.View.extend({
      tagName: 'ul',
      className: 'nav nav-list',
      initialize: function() {
        this.collection.on('reset', this.render, this);
        return this.collection.on('add', this.add, this);
      },
      render: function() {
        var currentCategory,
          _this = this;
        currentCategory = null;
        this.collection.each(function(pattern) {
          var child, patternObj;
          patternObj = pattern.toJSON();
          if (patternObj.category !== currentCategory) {
            _this.$el.append(separatorTmpl(patternObj));
            currentCategory = patternObj.category;
          }
          child = new PatternView({
            model: pattern
          });
          return _this.$el.append(child.render().$el).show();
        });
        return this;
      }
    });
    return View;
  });

}).call(this);
