// Generated by CoffeeScript 1.3.3
(function() {

  define(['backbone'], function(Backbone) {
    var View, template;
    template = _.template('<p><%= name %></p>');
    return View = Backbone.View.extend({
      tagName: 'li',
      className: 'pattern',
      initilize: function() {},
      render: function() {
        console.log('rendering patternview');
        console.log(this.model);
        this.$el.html(template(this.model.toJSON()));
        return this;
      }
    });
  });

}).call(this);
