// Generated by CoffeeScript 1.3.3
(function() {

  define(['underscore', 'backbone'], function(_, Backbone) {
    var Pattern, Patterns;
    Pattern = Backbone.Model.extend({
      url: 'js/models/patterns',
      validate: function(attrs) {
        if (_.isEmpty(attrs.name)) {
          return "Missing Name";
        }
      }
    });
    Patterns = Backbone.Collection.extend({
      model: Pattern,
      url: 'js/models/patterns',
      completed: function() {
        return this.where({
          completed: true
        });
      },
      remaining: function() {
        return this.where({
          completed: false
        });
      },
      comparator: function(model) {
        return model.get('name');
      }
    });
    return {
      Model: Pattern,
      Collection: Patterns
    };
  });

}).call(this);
